python ./crawl_paper/spiders/crawler_process_dantri/an_sinh_dantri.py
python ./crawl_paper/spiders/crawler_process_dantri/bat_dong_san.py
python ./crawl_paper/spiders/crawler_process_dantri/doi_song_dantri.py
python ./crawl_paper/spiders/crawler_process_dantri/du_lich_dantri.py
python ./crawl_paper/spiders/crawler_process_dantri/giai_tri_dantri.py
python ./crawl_paper/spiders/crawler_process_dantri/giao_duc_huong_nghiep_dantri.py
python ./crawl_paper/spiders/crawler_process_dantri/kinh_doanh_dantri.py
python ./crawl_paper/spiders/crawler_process_dantri/lao_dong_viec_lam_dantri.py
python ./crawl_paper/spiders/crawler_process_dantri/o_to_xe_may_dantri.py
python ./crawl_paper/spiders/crawler_process_dantri/phap_luat_dantri.py
python ./crawl_paper/spiders/crawler_process_dantri/suc_khoe_dantri.py
python ./crawl_paper/spiders/crawler_process_dantri/suc_manh_so_dantri.py
python ./crawl_paper/spiders/crawler_process_dantri/tam_long_nhan_ai_dantri.py
python ./crawl_paper/spiders/crawler_process_dantri/the_gioi_dantri.py
python ./crawl_paper/spiders/crawler_process_dantri/the_thao_dantri.py
python ./crawl_paper/spiders/crawler_process_dantri/tinh_yeu_gioi_tinh.py
python ./crawl_paper/spiders/crawler_process_dantri/van_hoa_dantri.py
python ./crawl_paper/spiders/crawler_process_dantri/xa_hoi_dantri.py