python ./crawl_paper/spiders/crawler_process_vietnamnet/ban_doc_vnn.py
python ./crawl_paper/spiders/crawler_process_vietnamnet/bat_dong_san_vnn.py
python ./crawl_paper/spiders/crawler_process_vietnamnet/doi_song_vnn.py
python ./crawl_paper/spiders/crawler_process_vietnamnet/du_lich_vnn.py
python ./crawl_paper/spiders/crawler_process_vietnamnet/giai_tri_vnn.py
python ./crawl_paper/spiders/crawler_process_vietnamnet/giao_duc_vnn.py
python ./crawl_paper/spiders/crawler_process_vietnamnet/kinh_doanh_vnn.py
python ./crawl_paper/spiders/crawler_process_vietnamnet/oto_xe_may_vnn.py
python ./crawl_paper/spiders/crawler_process_vietnamnet/phap_luat_vnn.py
python ./crawl_paper/spiders/crawler_process_vietnamnet/suc_khoe_vnn.py
python ./crawl_paper/spiders/crawler_process_vietnamnet/the_gioi_vnn.py
python ./crawl_paper/spiders/crawler_process_vietnamnet/the_thao_vnn.py
python ./crawl_paper/spiders/crawler_process_vietnamnet/thoi_su_vnn.py
python ./crawl_paper/spiders/crawler_process_vietnamnet/tuan_viet_nam_vnn.py